//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleMemberShip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commission
    {
        public Commission()
        {
            this.CommissionHistories = new HashSet<CommissionHistory>();
        }
    
        public int CommissionId { get; set; }
        public int CustomerId { get; set; }
        public int DealerId { get; set; }
        public int ProductId { get; set; }
        public decimal CommissionAmount { get; set; }
        public int PaymentStatusId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Dealer Dealer { get; set; }
        public virtual ICollection<CommissionHistory> CommissionHistories { get; set; }
    }
}
