//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleMemberShip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionHistory
    {
        public int CommissionHistoryId { get; set; }
        public int CommissionId { get; set; }
        public int ExistingCustomerId { get; set; }
        public int NewCustomerId { get; set; }
        public int ExistingDealerId { get; set; }
        public int NewDealerId { get; set; }
        public int ExistingProductId { get; set; }
        public int NewProductId { get; set; }
        public decimal ExistingCommissionAmount { get; set; }
        public decimal NewCommissionAmount { get; set; }
        public int ExistingPaymentStatusId { get; set; }
        public int NewPaymentStatusId { get; set; }
        public System.DateTime ActionDate { get; set; }
    
        public virtual Commission Commission { get; set; }
    }
}
