//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleMemberShip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public ProductCategory()
        {
            this.ProductCategoryMappings = new HashSet<ProductCategoryMapping>();
        }
    
        public int ProductCategoryId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ProductCategoryMapping> ProductCategoryMappings { get; set; }
    }
}
